version: 1
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Build & Publish Invoice Merger
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      enforce_admins: true
      restrictions: null

